DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzMzNzc4NzQ0LCJ1c2VySWQiOjJ9.uNhxyr-EgK8pAy0s-EB7Dbscc2hPLr2ALa7fsqosgrg